# Define lists of US and EU realms. Just once.
module Realms
  
  class WoW
    def self.us
      REALMS.select { |realm| realm[:region] == 'US' }
    end
    
    def self.us_by_timezone
      out = Hash.new

      REALMS.each do |realm|
        (out[realm[:timezone]] ||= Array.new) << realm
      end
      
      return out
    end
    
    def self.us_by_timezone_for_select
      out = Hash.new

      REALMS.each do |realm|
        (out[realm[:timezone]] ||= Array.new) << ["#{realm[:name]} (#{realm[:type].upcase})", realm[:name]]
      end
      
      return out
    end
  end
  
  protected

  REALMS = [
  	{:region => 'US', :timezone => 'Oceania', :name => "Barthilas", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Dreadmaul", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Frostmourne", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Gundrak", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Jubei'Thos", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Thaurissan", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Aman'Thul", :type => 'pve'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Caelestrasz", :type => 'pve'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Dath'Remar", :type => 'pve'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Khaz'goroth", :type => 'pve'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Nagrand", :type => 'pve'},
  	{:region => 'US', :timezone => 'Oceania', :name => "Saurfang", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Blackrock", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Blackwing Lair", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Bonechewer", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Boulderfist", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Coilfang", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Crushridge", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Daggerspine", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Dark Iron", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Darrowmere", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Destromath", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Dethecus", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Dragonmaw", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Dunemaul", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Frostwolf", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Gorgonnash", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Gurubashi", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Kalecgos", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Kil'Jaeden", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Lethon", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Maiev", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Nazjatar", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Ner'zhul", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Onyxia", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Rivendare", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Shattered Halls", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Spinebreaker", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Spirestone", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Stonemaul", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Stormscale", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Tichondrius", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Ursin", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Vashj", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Aerie Peak", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Anvilmar", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Arathor", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Antonidas", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Azuremyst", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Baelgun", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Blade's Edge", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Bladefist", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Bronzebeard", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Cenarius", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Draenor", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Dragonblight", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Echo Isles", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Galakrond", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Gnomeregan", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Hyjal", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Kilrogg", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Korialstrasz", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Lightbringer", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Misha", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Moonrunner", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Nordrassil", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Proudmoore", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Shadowsong", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Shu'Halo", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Silvermoon", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Skywall", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Suramar", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Uldum", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Uther", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Velen", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Windrunner", :type => 'pve'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Blackwater Raiders", :type => 'rp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Cenarion Circle", :type => 'rp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Feathermoon", :type => 'rp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Sentinels", :type => 'rp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Silver Hand", :type => 'rp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "The Scryers", :type => 'rp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "Wyrmrest Accord", :type => 'rp'},
  	{:region => 'US', :timezone => 'Pacific', :name => "The Venture Co.", :type => 'rp-pvp'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Kel'Thuzad", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Darkspear", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Deathwing", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Bloodscalp", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Nathrezim", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Azjol-Nerub", :type => 'pve'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Doomhammer", :type => 'pve'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Icecrown", :type => 'pve'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Perenolde", :type => 'pve'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Terenas", :type => 'pve'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Zangarmarsh", :type => 'pve'},
  	{:region => 'US', :timezone => 'Mountain', :name => "Shadow Council", :type => 'rp'},
  	{:region => 'US', :timezone => 'Central', :name => "Aegwynn", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Agamaggan", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Akama", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Archimonde", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Azgalor", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Azshara", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Balnazzar", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Blood Furnace", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Burning Legion", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Cho'gall", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Chromaggus", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Detheroc", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Drak'tharon", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Drak'thul", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Frostmane", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Garithos", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Gul'dan", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Hakkar", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Illidan", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Korgath", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Laughing Skull", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Mal'Ganis", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Malorne", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Mug'thol", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Stormreaver", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Sargeras", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "The Underbog", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Thunderlord", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Wildhammer", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Aggramar", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Alexstrasza", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Alleria", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Blackhand", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Borean Tundra", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Cairne", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Dawnbringer", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Draka", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Eitrigg", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Fizzcrank", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Garona", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Ghostlands", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Greymane", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Grizzly Hills", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Hellscream", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Hydraxis", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Kael'thas", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Khaz Modan", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Kul Tiras", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Madoran", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Malfurion", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Malygos", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Muradin", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Nesingwary", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Quel'Dorei", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Ravencrest", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Rexxar", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Runetotem", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Sen'Jin", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Staghelm", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Terokkar", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Thunderhorn", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Vek'nilash", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Whisperwind", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Winterhoof", :type => 'pve'},
  	{:region => 'US', :timezone => 'Central', :name => "Farstriders", :type => 'rp'},
  	{:region => 'US', :timezone => 'Central', :name => "Kirin Tor", :type => 'rp'},
  	{:region => 'US', :timezone => 'Central', :name => "Moon Guard", :type => 'rp'},
  	{:region => 'US', :timezone => 'Central', :name => "Scarlet Crusade", :type => 'rp'},
  	{:region => 'US', :timezone => 'Central', :name => "Sisters of Elune", :type => 'rp'},
  	{:region => 'US', :timezone => 'Central', :name => "Thorium Brotherhood", :type => 'rp'},
  	{:region => 'US', :timezone => 'Central', :name => "Emerald Dream", :type => 'rp-pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Lightninghoof", :type => 'rp-pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Maelstrom", :type => 'rp-pvp'},
  	{:region => 'US', :timezone => 'Central', :name => "Twisting Nether", :type => 'rp-pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Altar of Storms", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Alterac Mountains", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Andorhal", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Anetheron", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Anub'arak", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Arthas", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Auchindoun", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Black Dragonflight", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Bleeding Hollow", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Burning Blade", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Dalvengyr", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Demon Soul", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Dentarg", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Eredar", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Executus", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Firetree", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Gorefiend", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Haomarush", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Jaedenar", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Lightning's Blade", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Mannoroth", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Magtheridon", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Scilla", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Shadowmoon", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Shattered Hand", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Skullcrusher", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Smolderthorn", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "The Forgotten Coast", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Tortheldrin", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Warsong", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Ysondre", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Zuluhed", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Area 52", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Arygos", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Bloodhoof", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Dalaran", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Drenden", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Durotan", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Duskwood", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Eldre'Thalas", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Elune", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Eonar", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Exodar", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Fenris", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Garrosh", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Gilneas", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Kargath", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Khadgar", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Llane", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Lothar", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Medivh", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Nazgrel", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Norgannon", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Shandris", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Stormrage", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Tanaris", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Thrall", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Trollbane", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Turalyon", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Uldaman", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Undermine", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Ysera", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Zul'jin", :type => 'pve'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Argent Dawn", :type => 'rp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Earthen Ring", :type => 'rp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Steamwheedle Cartel", :type => 'rp'},
  	{:region => 'US', :timezone => 'Eastern', :name => "Ravenholdt", :type => 'rp-pvp'},
  	{:region => 'US', :timezone => 'Latin America', :name => "Drakkari", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Latin America', :name => "Ragnaros", :type => 'pvp'},
  	{:region => 'US', :timezone => 'Latin America', :name => "Quel'Thalas", :type => 'pve'}
  ]

  US_REALMS_BY_TZ = {
  	:oceania => [
  		{:name => "Barthilas", :type => 'pvp'},
  		{:name => "Dreadmaul", :type => 'pvp'},
  		{:name => "Frostmourne", :type => 'pvp'},
  		{:name => "Gundrak", :type => 'pvp'},
  		{:name => "Jubei'Thos", :type => 'pvp'},
  		{:name => "Thaurissan", :type => 'pvp'},
  		{:name => "Aman'Thul", :type => 'pve'},
  		{:name => "Caelestrasz", :type => 'pve'},
  		{:name => "Dath'Remar", :type => 'pve'},
  		{:name => "Khaz'goroth", :type => 'pve'},
  		{:name => "Nagrand", :type => 'pve'},
  		{:name => "Saurfang", :type => 'pve'}
  	],

  	:pacific => [
  		{:name => "Blackrock", :type => 'pvp'},
  		{:name => "Blackwing Lair", :type => 'pvp'},
  		{:name => "Bonechewer", :type => 'pvp'},
  		{:name => "Boulderfist", :type => 'pvp'},
  		{:name => "Coilfang", :type => 'pvp'},
  		{:name => "Crushridge", :type => 'pvp'},
  		{:name => "Daggerspine", :type => 'pvp'},
  		{:name => "Dark Iron", :type => 'pvp'},
  		{:name => "Darrowmere", :type => 'pvp'},
  		{:name => "Destromath", :type => 'pvp'},
  		{:name => "Dethecus", :type => 'pvp'},
  		{:name => "Dragonmaw", :type => 'pvp'},
  		{:name => "Dunemaul", :type => 'pvp'},
  		{:name => "Frostwolf", :type => 'pvp'},
  		{:name => "Gorgonnash", :type => 'pvp'},
  		{:name => "Gurubashi", :type => 'pvp'},
  		{:name => "Kalecgos", :type => 'pvp'},
  		{:name => "Kil'Jaeden", :type => 'pvp'},
  		{:name => "Lethon", :type => 'pvp'},
  		{:name => "Maiev", :type => 'pvp'},
  		{:name => "Nazjatar", :type => 'pvp'},
  		{:name => "Ner'zhul", :type => 'pvp'},
  		{:name => "Onyxia", :type => 'pvp'},
  		{:name => "Rivendare", :type => 'pvp'},
  		{:name => "Shattered Halls", :type => 'pvp'},
  		{:name => "Spinebreaker", :type => 'pvp'},
  		{:name => "Spirestone", :type => 'pvp'},
  		{:name => "Stonemaul", :type => 'pvp'},
  		{:name => "Stormscale", :type => 'pvp'},
  		{:name => "Tichondrius", :type => 'pvp'},
  		{:name => "Ursin", :type => 'pvp'},
  		{:name => "Vashj", :type => 'pvp'},
  		{:name => "Aerie Peak", :type => 'pve'},
  		{:name => "Anvilmar", :type => 'pve'},
  		{:name => "Arathor", :type => 'pve'},
  		{:name => "Antonidas", :type => 'pve'},
  		{:name => "Azuremyst", :type => 'pve'},
  		{:name => "Baelgun", :type => 'pve'},
  		{:name => "Blade's Edge", :type => 'pve'},
  		{:name => "Bladefist", :type => 'pve'},
  		{:name => "Bronzebeard", :type => 'pve'},
  		{:name => "Cenarius", :type => 'pve'},
  		{:name => "Draenor", :type => 'pve'},
  		{:name => "Dragonblight", :type => 'pve'},
  		{:name => "Echo Isles", :type => 'pve'},
  		{:name => "Galakrond", :type => 'pve'},
  		{:name => "Gnomeregan", :type => 'pve'},
  		{:name => "Hyjal", :type => 'pve'},
  		{:name => "Kilrogg", :type => 'pve'},
  		{:name => "Korialstrasz", :type => 'pve'},
  		{:name => "Lightbringer", :type => 'pve'},
  		{:name => "Misha", :type => 'pve'},
  		{:name => "Moonrunner", :type => 'pve'},
  		{:name => "Nordrassil", :type => 'pve'},
  		{:name => "Proudmoore", :type => 'pve'},
  		{:name => "Shadowsong", :type => 'pve'},
  		{:name => "Shu'Halo", :type => 'pve'},
  		{:name => "Silvermoon", :type => 'pve'},
  		{:name => "Skywall", :type => 'pve'},
  		{:name => "Suramar", :type => 'pve'},
  		{:name => "Uldum", :type => 'pve'},
  		{:name => "Uther", :type => 'pve'},
  		{:name => "Velen", :type => 'pve'},
  		{:name => "Windrunner", :type => 'pve'},
  		{:name => "Blackwater Raiders", :type => 'rp'},
  		{:name => "Cenarion Circle", :type => 'rp'},
  		{:name => "Feathermoon", :type => 'rp'},
  		{:name => "Sentinels", :type => 'rp'},
  		{:name => "Silver Hand", :type => 'rp'},
  		{:name => "The Scryers", :type => 'rp'},
  		{:name => "Wyrmrest Accord", :type => 'rp'},
  		{:name => "The Venture Co.", :type => 'rp-pvp'}
  	],

  	:mountain => [
  		{:name => "Kel'Thuzad", :type => 'pvp'},
  		{:name => "Darkspear", :type => 'pvp'},
  		{:name => "Deathwing", :type => 'pvp'},
  		{:name => "Bloodscalp", :type => 'pvp'},
  		{:name => "Nathrezim", :type => 'pvp'},
  		{:name => "Azjol-Nerub", :type => 'pve'},
  		{:name => "Doomhammer", :type => 'pve'},
  		{:name => "Icecrown", :type => 'pve'},
  		{:name => "Perenolde", :type => 'pve'},
  		{:name => "Terenas", :type => 'pve'},
  		{:name => "Zangarmarsh", :type => 'pve'},
  		{:name => "Shadow Council", :type => 'rp'}
  	],

  	:central => [
  		{:name => "Aegwynn", :type => 'pvp'},
  		{:name => "Agamaggan", :type => 'pvp'},
  		{:name => "Akama", :type => 'pvp'},
  		{:name => "Archimonde", :type => 'pvp'},
  		{:name => "Azgalor", :type => 'pvp'},
  		{:name => "Azshara", :type => 'pvp'},
  		{:name => "Balnazzar", :type => 'pvp'},
  		{:name => "Blood Furnace", :type => 'pvp'},
  		{:name => "Burning Legion", :type => 'pvp'},
  		{:name => "Cho'gall", :type => 'pvp'},
  		{:name => "Chromaggus", :type => 'pvp'},
  		{:name => "Detheroc", :type => 'pvp'},
  		{:name => "Drak'tharon", :type => 'pvp'},
  		{:name => "Drak'thul", :type => 'pvp'},
  		{:name => "Frostmane", :type => 'pvp'},
  		{:name => "Garithos", :type => 'pvp'},
  		{:name => "Gul'dan", :type => 'pvp'},
  		{:name => "Hakkar", :type => 'pvp'},
  		{:name => "Illidan", :type => 'pvp'},
  		{:name => "Korgath", :type => 'pvp'},
  		{:name => "Laughing Skull", :type => 'pvp'},
  		{:name => "Mal'Ganis", :type => 'pvp'},
  		{:name => "Malorne", :type => 'pvp'},
  		{:name => "Mug'thol", :type => 'pvp'},
  		{:name => "Stormreaver", :type => 'pvp'},
  		{:name => "Sargeras", :type => 'pvp'},
  		{:name => "The Underbog", :type => 'pvp'},
  		{:name => "Thunderlord", :type => 'pvp'},
  		{:name => "Wildhammer", :type => 'pvp'},
  		{:name => "Aggramar", :type => 'pve'},
  		{:name => "Alexstrasza", :type => 'pve'},
  		{:name => "Alleria", :type => 'pve'},
  		{:name => "Blackhand", :type => 'pve'},
  		{:name => "Borean Tundra", :type => 'pve'},
  		{:name => "Cairne", :type => 'pve'},
  		{:name => "Dawnbringer", :type => 'pve'},
  		{:name => "Draka", :type => 'pve'},
  		{:name => "Eitrigg", :type => 'pve'},
  		{:name => "Fizzcrank", :type => 'pve'},
  		{:name => "Garona", :type => 'pve'},
  		{:name => "Ghostlands", :type => 'pve'},
  		{:name => "Greymane", :type => 'pve'},
  		{:name => "Grizzly Hills", :type => 'pve'},
  		{:name => "Hellscream", :type => 'pve'},
  		{:name => "Hydraxis", :type => 'pve'},
  		{:name => "Kael'thas", :type => 'pve'},
  		{:name => "Khaz Modan", :type => 'pve'},
  		{:name => "Kul Tiras", :type => 'pve'},
  		{:name => "Madoran", :type => 'pve'},
  		{:name => "Malfurion", :type => 'pve'},
  		{:name => "Malygos", :type => 'pve'},
  		{:name => "Muradin", :type => 'pve'},
  		{:name => "Nesingwary", :type => 'pve'},
  		{:name => "Quel'Dorei", :type => 'pve'},
  		{:name => "Ravencrest", :type => 'pve'},
  		{:name => "Rexxar", :type => 'pve'},
  		{:name => "Runetotem", :type => 'pve'},
  		{:name => "Sen'Jin", :type => 'pve'},
  		{:name => "Staghelm", :type => 'pve'},
  		{:name => "Terokkar", :type => 'pve'},
  		{:name => "Thunderhorn", :type => 'pve'},
  		{:name => "Vek'nilash", :type => 'pve'},
  		{:name => "Whisperwind", :type => 'pve'},
  		{:name => "Winterhoof", :type => 'pve'},
  		{:name => "Farstriders", :type => 'rp'},
  		{:name => "Kirin Tor", :type => 'rp'},
  		{:name => "Moon Guard", :type => 'rp'},
  		{:name => "Scarlet Crusade", :type => 'rp'},
  		{:name => "Sisters of Elune", :type => 'rp'},
  		{:name => "Thorium Brotherhood", :type => 'rp'},
  		{:name => "Emerald Dream", :type => 'rp-pvp'},
  		{:name => "Lightninghoof", :type => 'rp-pvp'},
  		{:name => "Maelstrom", :type => 'rp-pvp'},
  		{:name => "Twisting Nether", :type => 'rp-pvp'}
  	],

  	:eastern => [
  		{:name => "Altar of Storms", :type => 'pvp'},
  		{:name => "Alterac Mountains", :type => 'pvp'},
  		{:name => "Andorhal", :type => 'pvp'},
  		{:name => "Anetheron", :type => 'pvp'},
  		{:name => "Anub'arak", :type => 'pvp'},
  		{:name => "Arthas", :type => 'pvp'},
  		{:name => "Auchindoun", :type => 'pvp'},
  		{:name => "Black Dragonflight", :type => 'pvp'},
  		{:name => "Bleeding Hollow", :type => 'pvp'},
  		{:name => "Burning Blade", :type => 'pvp'},
  		{:name => "Dalvengyr", :type => 'pvp'},
  		{:name => "Demon Soul", :type => 'pvp'},
  		{:name => "Dentarg", :type => 'pvp'},
  		{:name => "Eredar", :type => 'pvp'},
  		{:name => "Executus", :type => 'pvp'},
  		{:name => "Firetree", :type => 'pvp'},
  		{:name => "Gorefiend", :type => 'pvp'},
  		{:name => "Haomarush", :type => 'pvp'},
  		{:name => "Jaedenar", :type => 'pvp'},
  		{:name => "Lightning's Blade", :type => 'pvp'},
  		{:name => "Mannoroth", :type => 'pvp'},
  		{:name => "Magtheridon", :type => 'pvp'},
  		{:name => "Scilla", :type => 'pvp'},
  		{:name => "Shadowmoon", :type => 'pvp'},
  		{:name => "Shattered Hand", :type => 'pvp'},
  		{:name => "Skullcrusher", :type => 'pvp'},
  		{:name => "Smolderthorn", :type => 'pvp'},
  		{:name => "The Forgotten Coast", :type => 'pvp'},
  		{:name => "Tortheldrin", :type => 'pvp'},
  		{:name => "Warsong", :type => 'pvp'},
  		{:name => "Ysondre", :type => 'pvp'},
  		{:name => "Zuluhed", :type => 'pvp'},
  		{:name => "Area 52", :type => 'pve'},
  		{:name => "Arygos", :type => 'pve'},
  		{:name => "Bloodhoof", :type => 'pve'},
  		{:name => "Dalaran", :type => 'pve'},
  		{:name => "Drenden", :type => 'pve'},
  		{:name => "Durotan", :type => 'pve'},
  		{:name => "Duskwood", :type => 'pve'},
  		{:name => "Eldre'Thalas", :type => 'pve'},
  		{:name => "Elune", :type => 'pve'},
  		{:name => "Eonar", :type => 'pve'},
  		{:name => "Exodar", :type => 'pve'},
  		{:name => "Fenris", :type => 'pve'},
  		{:name => "Garrosh", :type => 'pve'},
  		{:name => "Gilneas", :type => 'pve'},
  		{:name => "Grizzly Hills", :type => 'pve'},
  		{:name => "Kargath", :type => 'pve'},
  		{:name => "Khadgar", :type => 'pve'},
  		{:name => "Llane", :type => 'pve'},
  		{:name => "Lothar", :type => 'pve'},
  		{:name => "Medivh", :type => 'pve'},
  		{:name => "Nazgrel", :type => 'pve'},
  		{:name => "Norgannon", :type => 'pve'},
  		{:name => "Shandris", :type => 'pve'},
  		{:name => "Stormrage", :type => 'pve'},
  		{:name => "Tanaris", :type => 'pve'},
  		{:name => "Thrall", :type => 'pve'},
  		{:name => "Trollbane", :type => 'pve'},
  		{:name => "Turalyon", :type => 'pve'},
  		{:name => "Uldaman", :type => 'pve'},
  		{:name => "Undermine", :type => 'pve'},
  		{:name => "Ysera", :type => 'pve'},
  		{:name => "Zul'jin", :type => 'pve'},
  		{:name => "Argent Dawn", :type => 'rp'},
  		{:name => "Earthen Ring", :type => 'rp'},
  		{:name => "Steamwheedle Cartel", :type => 'rp'},
  		{:name => "Ravenholdt", :type => 'rp-pvp'}
  	],

  	:latin_america => [
  		{:name => "Drakkari", :type => 'pvp'},
  		{:name => "Ragnaros", :type => 'pvp'},
  		{:name => "Quel'Thalas", :type => 'pve'}
  	]
  }

  
end